### PR TITLE
Fix overlooked 'and' operator...

### PR DESCRIPTION
**Pull request by vcrhonek**
...instead of list of parameters for ansible condition.

### CODE REVIEW

**Comment by mlichvar** [comment]
Looks good to me.

**Comment by pcahyna** [comment]
this is just cosmetic followup to #36, or does it fix a real problem?

**Comment by vcrhonek** [comment]
> this is just cosmetic followup to #36, or does it fix a real problem?

Just cosmetic followup to #36.

**Comment by pcahyna** [comment]
[citest bad]

**Comment by yontalcar** [comment]
[citest bad]

**Comment by vcrhonek** [comment]
This PR is obsolete since merge of PR#52, commit e145b8cda93dbbd64aba2d049ed562b29b974ae5.

**Pull request closed without merging**
