### PR TITLE
Use service_facts instead of chkconfig/systemctl

### PR DESCRIPTION
**Pull request by pavel-z1**
In the issue #81  @richm proposed to use ansible service_facts instead of chkconfig/systemctl for different operation systems.

Updated logic more compact.

### CODE REVIEW

**Comment by pavel-z1** [comment]
As I see, molecule test errors not related to this PR.

**Comment by richm** [comment]
[citest commit:fc1daf953d0c2cc8147a434283bfaee9e43f0376]

**Comment by richm** [comment]
lgtm

**Review by richm — APPROVED** [review]

**Comment by richm** [comment]
@mlichvar ok to merge?

**Comment by mlichvar** [comment]
Looks good to me. Thanks.

**Pull request merged**
