### PR TITLE
more ansible-lint 6.x fixes

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
@mlichvar the fedora tests are failing:
```
TASK [Check if SW/HW timestamping is supported] ********************************
task path: /WORKDIR/dist-git-timesync-more-ansible-lint-fixes-7be4cgdu/tests/tests_ntp_ptp.yml:33
Tuesday 10 January 2023  05:01:51 +0000 (0:00:00.629)       0:00:33.367 ******* 
fatal: [sut]: FAILED! => {
    "changed": false,
    "cmd": "ethtool -T eth0",
    "rc": 2
}

MSG:

[Errno 2] No such file or directory: b'ethtool'
...ignoring
```
Looking at the output, I do not see the `ethtool` package being installed.  Is there some dependency that was changed on Fedora, and now `ethtool` is not being installed?  Should I add a check to the test to install `ethtool`?

**Comment by mlichvar** [comment]
I looked in changes in the recursive set of packages that depend on ethtool and the comps, but didn't see anything relevant.

Yes, please install ethtool for the tests. Thanks.

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
@mlichvar The Fedora ptp tests are failing like this: https://dl.fedoraproject.org/pub/alt/linuxsystemroles/logs/lsr-citool_timesync-168-6e0d787_Fedora-37_20230110-233007/artifacts/tests_ptp_single-FAILED.log
```
TASK [Run pmc] *****************************************************************
task path: /WORKDIR/dist-git-timesync-more-ansible-lint-fixes-5pf7rru0/tests/tests_ptp_single.yml:37
Tuesday 10 January 2023  23:29:45 +0000 (0:00:04.431)       0:01:38.708 ******* 
ok: [sut] => {
    "changed": false,
    "cmd": [
        "pmc",
        "-u",
        "-b",
        "0",
        "-d",
        "3",
        "GET DOMAIN",
        "GET PORT_DATA_SET"
    ],
    "delta": "0:00:00.104527",
    "end": "2023-01-10 23:29:46.161557",
    "rc": 0,
    "start": "2023-01-10 23:29:46.057030"
}

STDOUT:

sending: GET DOMAIN
sending: GET PORT_DATA_SET

TASK [Check PTP domain] ********************************************************
task path: /WORKDIR/dist-git-timesync-more-ansible-lint-fixes-5pf7rru0/tests/tests_ptp_single.yml:42
Tuesday 10 January 2023  23:29:46 +0000 (0:00:01.349)       0:01:40.057 ******* 
fatal: [sut]: FAILED! => {
    "assertion": "'domainNumber 3' in pmc.stdout",
    "changed": false,
    "evaluated_to": false
}

MSG:

Assertion failed
```
I don't see "domainNumber" in the pmc output on Fedora 36 or Fedora 37.  Has it changed?  Do we need a fix for the test?

**Comment by mlichvar** [comment]
The pmc output indicates missing responses from ptp4l. Probably selinux breaking things again.

**Comment by richm** [comment]
> The pmc output indicates missing responses from ptp4l. Probably selinux breaking things again.

That's it.  Disabling selinux makes the tests pass.

**Comment by mlichvar** [comment]
It is probably https://bugzilla.redhat.com/show_bug.cgi?id=2159919. Fix in progress...

**Comment by richm** [comment]
> It is probably https://bugzilla.redhat.com/show_bug.cgi?id=2159919. Fix in progress...

Ok.  Then it looks like this PR is good - going to merge it.

**Pull request merged**
