### PR TITLE
tag tests with slow

### PR DESCRIPTION
**Pull request by richm**
Tag some tests that are slow, to skip for fast basic smoke testing

### CODE REVIEW

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Review by nhosoi — APPROVED** [review]
lgtm

I'm curious why this particular test tests_default_wrapper.yml is slower than the others?
Due to `import_playbook` and/or running in `check_mode`?

**Comment by richm** [comment]
> lgtm
> 
> I'm curious why this particular test tests_default_wrapper.yml is slower than the others?
> Due to `import_playbook` and/or running in `check_mode`?

I don't know - @xjezda00 or @pcahyna ?

**Comment by richm** [comment]
If there are no further objections I'd like to merge this

**Comment by nhosoi** [comment]
> If there are no further objections I'd like to merge this

No objections from me.

**Pull request merged**
