### PR TITLE
Add delay_mechanism option to PTP domain

### PR DESCRIPTION
**Pull request by nolta**
For setting `delay_mechanism` to `P2P`.

### CODE REVIEW

**Comment by richm** [comment]
Thanks for your patch!
Could you add a test for this?  It doesn't have to be a new test file, perhaps an addition to an existing test in `tests/tests_*.yml`?

**Comment by nolta** [comment]
Sure, i can try. Is it possible to run the tests locally?

**Comment by richm** [comment]
> Sure, i can try. Is it possible to run the tests locally?

If you are using Fedora or CentOS or RHEL, see https://linux-system-roles.github.io/contribute.html

You'll need to install tox and tox-lsr.  And also `standard-test-roles-inventory-qemu`.  Your system should support KVM.

Download the config file from https://raw.githubusercontent.com/linux-system-roles/linux-system-roles.github.io/master/download/linux-system-roles.json to `~/.config/linux-system-roles.json`

Then you can run the tests locally like this: `tox -e qemu-ansible-core-2.12 -- --image-name centos-8 tests/tests_default.yml`

Note that you may run into errors if you are using some other VMs on your system using some other hypervisor like `virtualbox`.

Check the `artifacts/` directory - there are some log files there that may help debug problems.

**Comment by richm** [comment]
any update?

**Pull request closed without merging**
