### PR TITLE
Configure Molecule and Travis CI (this PR should trigger build in CI)

### PR DESCRIPTION
**Pull request by vcrhonek**
Configures Molecule to do basic checks (lint/syntax, run, idempotence, Ansible check mode functionality) of the role with default parameters (tests/tests_default.yml) using Travis CI and centos6/7 docker containers.

### CODE REVIEW

**Comment by vcrhonek** [comment]
https://travis-ci.org/linux-system-roles/timesync

**Comment by vcrhonek** [comment]
To make the build pass, we need to resolve PR#28, PR#30 and ISSUE#31.

**Comment by pcahyna** [comment]
@vcrhonek it looks like Molecule stops on first error. Therefore, one does not see that one needs to merge #28 until one merges #30 and reruns the CI again. Is there a way to make Molecule show all errors, i.e. execute all actions?

**Comment by vcrhonek** [comment]
@pcahyna I don't think so. I believe we've already discussed it in the context of skipping lint warnings:
https://github.com/ansible/molecule/issues/1308

We can run multiple molecule commands in .travis.yml to see errors from multiple actions.

But the test matrix differs for each command. For example, "molecule converge" runs dependency, create, prepare, converge (thus it won't fail on lint/syntax errors), "molecule check" runs  destroy, dependency, create, prepare, converge, check, destroy (thus it won't fail on lint/syntax errors, but could fail during converge and skip check because of that). I don't know whether test matrix is configurable for these commands in the same manner as it is for "molecule test" (and don't see it with quick look into Molecule's documentation).

**Comment by pcahyna** [comment]
@vcrhonek I understood that lint warnings issue as being a bit different: I thought that it was about warning not being treated as errors, while here I would like Molecule to continue to the next step, even if something is treated as an error.

> But the test matrix differs for each command. For example, "molecule converge" runs dependency, create, prepare, converge (thus it won't fail on lint/syntax errors), "molecule check" runs destroy, dependency, create, prepare, converge, check, destroy (thus it won't fail on lint/syntax errors, but could fail during converge and skip check because of that). 

I think it is fine for "molecule check" to skip check if converge fails. So "molecule check" may be the right thing for us.

> I don't know whether test matrix is configurable for these commands in the same manner as it is for "molecule test" (and don't see it with quick look into Molecule's documentation).

Maybe we don't need it, wouldn't the default sequence for "molecule check" be fine for us?

**Comment by vcrhonek** [comment]
@pcahyna I see. We can run "molecule lint", "molecule syntax" and "molecule check" then. The first two will cover lint/syntax separately, the third will cover running the role and running the role in check mode if the first step succeeds.

**Comment by vcrhonek** [comment]
I forgot idempotence. Will think about it.

**Comment by pcahyna** [comment]
@vcrhonek doesn't this mean that you can configure the sequence (matrix) for all commands, not just "test"? https://molecule.readthedocs.io/en/latest/configuration.html#scenario ? There is check_sequence, converge_sequence

**Comment by vcrhonek** [comment]
> @vcrhonek doesn't this mean that you can configure the sequence (matrix) for all commands, not just "test"? https://molecule.readthedocs.io/en/latest/configuration.html#scenario ? There is check_sequence, converge_sequence

Yes, it does. I wasn't able to find.

**Comment by pcahyna** [comment]
One can then configure either the converge or check command to run all of converge, check and idempotence, or configure "test" to do it (and skip syntax checking).

**Comment by vcrhonek** [comment]
> One can then configure either the converge or check command to run all of converge, check and idempotence, or configure "test" to do it (and skip syntax checking).

Yes, that's exactly what I did locally (reconfigured test to do converge, idempotence and check). I'm going to update PR.

**Pull request merged**
