### PR TITLE
Fix iburst and add new options

### PR DESCRIPTION
**Pull request by mlichvar**
The first patch fixes the issue #70. The second patchs adds the prefer option as requested in issue #61 and also the trust option.

### CODE REVIEW

**Comment by richm** [comment]
lgtm - but not familiar with this role - @pcahyna ?

**Comment by mlichvar** [comment]
Added tests.

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
needs rebase

**Comment by mlichvar** [comment]
It seems this was squashed and merged with the NTS support in #83.

**Pull request closed without merging**
