### PR TITLE
Rename timesync_ntp_provider_default to timesync_ntp_provider_os_default

### PR DESCRIPTION
**Pull request by pcahyna**
for consistency with network, see https://github.com/linux-system-roles/network/issues/71

### CODE REVIEW

**Comment by mlichvar** [comment]
Makes sense to me.

**Comment by tyll** [comment]
Should this maybe be `timesync_provider_os_default` The network role also uses `$ROLENAME_provider_os_default`.

**Comment by mlichvar** [comment]
The "ntp" makes it clear that it configures the NTP provider. There is a theoretical possibility that multiple PTP providers will be supported and a variable may be needed to allow the user to select between them.

**Comment by tyll** [comment]
Are NTP and PTP configured at the same time or will only one of them be running at the same time? If it is only one of them, then `timesync_provider_os_default` can point to the provider that is used for the system that is currently configured, e.g. chrony when ntp is used or linuxptp when ptp is active.

**Comment by mlichvar** [comment]
The role allows PTP and NTP to be configured at the same time. In this case the clock is controlled by chronyd/ntpd and ptp4l/phc2sys are configured as SHM reference clocks for the PTP time sources.

**Comment by tyll** [comment]
[¢itest bad]

**Comment by tyll** [comment]
[citest all]

**Pull request merged**
