### PR TITLE
Add refclock support, used for VM using ptp clock of ESX

### PR DESCRIPTION
**Pull request by Ofthestreet**
Enhancement: Be able to configure chrony using the refclock parameter. 

Reason: We configure the VM timesync using the Precision Clock feature of the ESX

Result: new variable in chrony.conf

Issue Tracker Tickets (Jira or BZ if any):

### CODE REVIEW

**Comment by Ofthestreet** [comment]
You are completely right... Sorry

Le ven. 8 déc. 2023, 16:00, Richard Megginson ***@***.***> a
écrit :

**Comment by richm** [comment]
> You are completely right... Sorry 

No worries.  Will you close this PR, or shall I?

**Comment by Ofthestreet** [comment]
This was my very first pull request ever done on GitHub, I was a bit prood
☺️

You can close it if you want unless I will do it on Monday

Le ven. 8 déc. 2023, 20:33, Richard Megginson ***@***.***> a
écrit :

**Comment by richm** [comment]
> This was my very first pull request ever done on GitHub, I was a bit prood ☺️ 

cool :-)

> You can close it if you want unless I will do it on Monday

ok - I'll leave it up for a while in case you want to show it to someone

**Comment by Ofthestreet** [comment]
I will detete my branch and this pull request, thanks @richm

**Pull request closed without merging**
