### PR TITLE
Add default vars test

### PR DESCRIPTION
**Pull request by i386x**
Add test that checks the role defines all its parameters in defaults.

### CODE REVIEW

**Comment by pcahyna** [comment]
This is in analogy with https://github.com/linux-system-roles/selinux/pull/43 and tests the problem fixed in PR #15

**Comment by mlichvar** [comment]
There is a typo in `declares all paremeters`. Other than that it looks good to me. Thanks.

**Comment by pcahyna** [comment]
it should use `version` instead of `version_compare`: #23 https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#version-comparison

**Comment by pcahyna** [comment]
#57 fixes that#57

**Pull request merged**
