### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
@mlichvar any idea why chronyd cannot start in a container?  This was working up until a couple of days ago.

**Comment by mlichvar** [comment]
chronyd as the daemon, or the systemd service? Is there an error message?

**Comment by richm** [comment]
> chronyd as the daemon, or the systemd service? Is there an error message?

The systemd service fails - chronyd cannot create the /var/run/chronyd/chroynd.pid file: https://github.com/linux-system-roles/timesync/pull/109/checks?check_run_id=2027876986 - scroll down until you see `Molecule default > converge` - click on the triangle to expand the output - then scroll down to `Enable chronyd`
```
  ● chronyd.service - NTP client/server
     Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2021-03-04 03:52:24 UTC; 4s ago
       Docs: man:chronyd(8)
             man:chrony.conf(5)
    Process: 859 ExecStart=/usr/sbin/chronyd $OPTIONS (code=exited, status=1/FAILURE)
  
  Mar 04 03:52:24 centos-8 systemd[1]: Starting NTP client/server...
  Mar 04 03:52:24 centos-8 chronyd[870]: chronyd version 3.5 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SIGND +ASYNCDNS +SECHASH +IPV6 +DEBUG)
  Mar 04 03:52:24 centos-8 chronyd[870]: Fatal error : Could not open /var/run/chrony/chronyd.pid : Permission denied
  Mar 04 03:52:24 centos-8 chronyd[859]: Could not open /var/run/chrony/chronyd.pid : Permission denied
  Mar 04 03:52:24 centos-8 systemd[1]: chronyd.service: Control process exited, code=exited status=1
  Mar 04 03:52:24 centos-8 systemd[1]: chronyd.service: Failed with result 'exit-code'.
  Mar 04 03:52:24 centos-8 systemd[1]: Failed to start NTP client/server.
```
The output also contains various other debugging - afaict there are no selinux issues

**Comment by richm** [comment]
hmm - it is working on my local centos7 vm using docker . . .

**Comment by mlichvar** [comment]
If it's not selinux (I didn't see in the logs anything suggesting it's not), I'd guess chronyd lost the DAC_OVERRIDE capability, which is required to write the pidfile in a directory owned by the chrony user.

**Comment by richm** [comment]
> If it's not selinux (I didn't see in the logs anything suggesting it's not), I'd guess chronyd lost the DAC_OVERRIDE capability, which is required to write the pidfile in a directory owned by the chrony user.

Is there some way to tell for sure if this is the problem or not?

**Comment by mlichvar** [comment]
You can add the following line to the chronyd unit file and see what capabilities are printed in the log:
````
ExecStartPre=/usr/sbin/capsh --print
````

**Comment by richm** [comment]
@mlichvar - this is what `capsh` says:
```
          "Mar 09 18:15:42 centos-8 capsh[953]:  secure-no-ambient-raise: no (unlocked)",
          "Mar 09 18:15:42 centos-8 capsh[953]: uid=0(root)",
          "Mar 09 18:15:42 centos-8 capsh[953]: gid=0(root)",
          "Mar 09 18:15:42 centos-8 capsh[953]: groups=",
          "Mar 09 18:15:42 centos-8 chronyd[971]: chronyd version 3.5 starting (+CMDMON +NTP +REFCLOCK +RTC +PRIVDROP +SCFILTER +SIGND +ASYNCDNS +SECHASH +IPV6 +DEBUG)",
          "Mar 09 18:15:42 centos-8 chronyd[971]: Fatal error : Could not open /var/run/chrony/chronyd.pid : Permission denied",
          "Mar 09 18:15:42 centos-8 chronyd[964]: Could not open /var/run/chrony/chronyd.pid : Permission denied",
```
not sure what this means

**Comment by richm** [comment]
this is what capsh says normally on a centos-8 system
```
Mar 09 21:02:39 localhost capsh[5843]:  secure-noroot: no (unlocked)
Mar 09 21:02:39 localhost capsh[5843]:  secure-no-suid-fixup: no (unlocked)
Mar 09 21:02:39 localhost capsh[5843]:  secure-keep-caps: no (unlocked)
Mar 09 21:02:39 localhost capsh[5843]:  secure-no-ambient-raise: no (unlocked)
Mar 09 21:02:39 localhost capsh[5843]: uid=0(root)
Mar 09 21:02:39 localhost capsh[5843]: gid=0(root)
Mar 09 21:02:39 localhost capsh[5843]: groups=
```

**Comment by richm** [comment]
this is what I see when I run it in docker 20 container:
```
        "Mar 09 21:15:32 centos-8 capsh[762]: Securebits: 00/0x0/1'b0",^[[0m
        "Mar 09 21:15:32 centos-8 capsh[762]:  secure-noroot: no (unlocked)",^[[0m
        "Mar 09 21:15:32 centos-8 capsh[762]:  secure-no-suid-fixup: no (unlocked)",^[[0m
        "Mar 09 21:15:32 centos-8 capsh[762]:  secure-keep-caps: no (unlocked)",^[[0m
        "Mar 09 21:15:32 centos-8 capsh[762]:  secure-no-ambient-raise: no (unlocked)",^[[0m
        "Mar 09 21:15:32 centos-8 capsh[762]: uid=0(root)",^[[0m
        "Mar 09 21:15:32 centos-8 capsh[762]: gid=0(root)",^[[0m
        "Mar 09 21:15:32 centos-8 capsh[762]: groups=",^[[0m
```

**Comment by mlichvar** [comment]
There should be two lines before that part, listing current and bounding set, e.g.
Current: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,...
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,...

If that's missing, I guess the process is not even allowed to check its own capabilities?

**Comment by jharuda** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Pull request closed without merging**
