### PR TITLE
use `is version` instead of deprecated `is version_compare`

### PR DESCRIPTION
**Pull request by pcahyna**

### CODE REVIEW

**Comment by tyll** [comment]
CentOS 6 error:

```
TASK [linux-system-roles.timesync : Generate timemaster.conf file] *************
task path: /tmp/tmpp_7tbdnd/tasks/main.yml:167
fatal: [/cache/CentOS-6-x86_64-GenericCloud-1901.qcow2c]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'chrony'"}
```

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
I don't think we need this PR anymore since we only support ansible version 2.7 and later.
I'm going to close this PR unless there are any objections.

**Pull request closed without merging**
